language: php

php:
  - '7.0.33'
  - '7.1.25'
  - '7.2.13'
  - '7.3.0'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: 
  - vendor/bin/pds-skeleton validate
  - vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)
